# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["**/*.json", "**/*.svg", "NOTICE", "**/*.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.png"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jack Henry"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [ "jh-consumer-tools/fonts/*.woff2"
]
precedence = "override"
SPDX-License-Identifier = "OFL-1.1"
SPDX-FileCopyrightText = "Copyright 2011 The Roboto Project Authors"
