name: Publish
on:
  # JR: disable publish on push until we're ready to go live
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '**/*.md'
  workflow_dispatch: {}

jobs:
  publish-packages:
    name: Publish Packages
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: YARN_ENABLE_COLORS=true yarn install
      - name: Publish packages to npm
        run: |
          yarn install
          yarn build
          yarn release
