name: Publish
on:
  # Triggered by completed Test runs
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]
  workflow_dispatch: {}

jobs:
  publish-packages:
    name: Publish Packages
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write  # Required for OIDC
      contents: write # required for github release and package.json version updates via lerna
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: YARN_ENABLE_COLORS=true yarn install

      - name: Publish packages to npm

        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          yarn build
          yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # used for lerna version via lerna publish --create-release github